from typing import Callable, Optional, TypedDict

import numpy as np
from numpy.typing import ArrayLike, NDArray

INTEGRATORS: list[str]

class Trajectory:
    t: NDArray[np.float64]  # (F,)
    pos: NDArray[np.float64]  # (F, N, 3)
    vel: NDArray[np.float64]  # (F, N, 3)
    kinetic: NDArray[np.float64]  # (F,)
    potential: NDArray[np.float64]  # (F,)
    energy: NDArray[np.float64]  # (F,)
    n_particles: int
    n_frames: int
    def __len__(self) -> int: ...

class UniformField:
    g: NDArray[np.float64]
    def __init__(self, g: ArrayLike) -> None: ...

class NewtonianGravity:
    G: float
    softening: float
    def __init__(self, G: float = 1.0, softening: float = 0.0) -> None: ...

class Spring:
    def __init__(self, i: int, j: int, k: float, rest_length: float) -> None: ...

class AnchorSpring:
    def __init__(self, i: int, anchor: ArrayLike, k: float, rest_length: float = 0.0) -> None: ...

class LinearDrag:
    def __init__(self, gamma: float) -> None: ...

class QuadraticDrag:
    def __init__(self, c: float) -> None: ...

class CustomForce:
    def __init__(
        self,
        acceleration: Callable[[float, NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]], ArrayLike],
        potential: Optional[Callable[[float, NDArray[np.float64], NDArray[np.float64]], float]] = None,
        velocity_dependent: bool = True,
        name: Optional[str] = None,
    ) -> None: ...

Force = UniformField | NewtonianGravity | Spring | AnchorSpring | LinearDrag | QuadraticDrag | CustomForce

class IntegratorInfo(TypedDict):
    name: str
    order: int
    symplectic: bool

class World:
    integrator: str
    t: float
    positions: NDArray[np.float64]
    velocities: NDArray[np.float64]
    masses: NDArray[np.float64]
    @property
    def pinned(self) -> NDArray[np.bool_]: ...
    @property
    def n_particles(self) -> int: ...
    @property
    def forces(self) -> dict[int, str]: ...
    @property
    def integrator_info(self) -> IntegratorInfo: ...
    def __init__(self, integrator: str = "verlet") -> None: ...
    def add_particle(self, pos: ArrayLike, vel: Optional[ArrayLike] = None, mass: float = 1.0) -> int: ...
    def remove_particle(self, i: int) -> None: ...
    def pin(self, i: int, pinned: bool = True) -> None: ...
    def add_force(self, force: Force) -> int: ...
    def remove_force(self, id: int) -> None: ...
    def replace_force(self, id: int, force: Force) -> None: ...
    def force_params(self, id: int) -> dict[str, float | NDArray[np.float64]]: ...
    def set_force_params(self, id: int, **params: float | ArrayLike) -> None: ...
    def clear_forces(self) -> None: ...
    def step(self, dt: float, n: int = 1) -> None: ...
    def run(self, dt: float, steps: int, record_every: int = 1) -> Trajectory: ...
    def accelerations(self) -> NDArray[np.float64]: ...
    def kinetic_energy(self) -> float: ...
    def potential_energy(self) -> float: ...
    def total_energy(self) -> float: ...
    def momentum(self) -> NDArray[np.float64]: ...
    def angular_momentum(self) -> NDArray[np.float64]: ...
    def center_of_mass(self) -> NDArray[np.float64]: ...
